import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';
import GlobalState from "@/context/page";
import Navbar from "@/components/Navbar/page";
import { AuthProvider } from "@/context/auth";
import { ToastContainer } from 'react-toastify';
import { CartProvider } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "fahasa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AuthProvider>
        <GlobalState>  
          <CartProvider>
            <Navbar/>
            <main className="flex min-h-screen flex-col mt-[65px]"> {children}
              <ToastContainer position="top-right" autoClose={3000} />
            </main>
            <Footer/>
          </CartProvider>
        </GlobalState>
         </AuthProvider>
      </body>
    </html>
  );
}
